DELIMITER $$
    CREATE DEFINER=`root`@`localhost` PROCEDURE `users_add`(
    in _username varchar(80),in _email varchar(254),in _password varchar(60),in _is_admin int(10) unsigned,in _created_at datetime,in _updated_at datetime,in _username varchar(80),in _email varchar(254),in _password varchar(60),in _is_admin int(10) unsigned,in _created_at datetime,in _updated_at datetime,in _username varchar(80),in _email varchar(254),in _password varchar(60),in _created_at datetime,in _updated_at datetime,in _username varchar(80),in _email varchar(254),in _password varchar(60),in _created_at datetime,in _updated_at datetime,in _USER char(32),in _CURRENT_CONNECTIONS bigint(20),in _TOTAL_CONNECTIONS bigint(20),in _username varchar(80),in _email varchar(254),in _password varchar(60),in _is_admin int(10) unsigned,in _created_at datetime,in _updated_at datetime,in _username varchar(80),in _email varchar(254),in _password varchar(60),in _is_admin int(10) unsigned,in _created_at datetime,in _updated_at datetime,in _username varchar(80),in _email varchar(254),in _password varchar(60),in _created_at datetime,in _updated_at datetime,in _username varchar(80),in _email varchar(254),in _password varchar(60),in _created_at datetime,in _updated_at datetime,in _USER char(32),in _CURRENT_CONNECTIONS bigint(20),in _TOTAL_CONNECTIONS bigint(20),in _username varchar(80),in _email varchar(254),in _password varchar(60),in _is_admin int(10) unsigned,in _created_at datetime,in _updated_at datetime,in _username varchar(80),in _email varchar(254),in _password varchar(60),in _is_admin int(10) unsigned,in _created_at datetime,in _updated_at datetime,in _username varchar(80),in _email varchar(254),in _password varchar(60),in _created_at datetime,in _updated_at datetime,in _username varchar(80),in _email varchar(254),in _password varchar(60),in _created_at datetime,in _updated_at datetime,in _USER char(32),in _CURRENT_CONNECTIONS bigint(20),in _TOTAL_CONNECTIONS bigint(20),in _username varchar(80),in _email varchar(254),in _password varchar(60),in _is_admin int(10) unsigned,in _created_at datetime,in _updated_at datetime,in _username varchar(80),in _email varchar(254),in _password varchar(60),in _is_admin int(10) unsigned,in _created_at datetime,in _updated_at datetime,in _username varchar(80),in _email varchar(254),in _password varchar(60),in _created_at datetime,in _updated_at datetime,in _username varchar(80),in _email varchar(254),in _password varchar(60),in _created_at datetime,in _updated_at datetime,in _USER char(32),in _CURRENT_CONNECTIONS bigint(20),in _TOTAL_CONNECTIONS bigint(20))
    BEGIN
        
        insert into users values(UUID(),_username, _email, _password, _is_admin, _created_at, _updated_at, UUID(),_username, _email, _password, _is_admin, _created_at, _updated_at, UUID(),_username, _email, _password, _created_at, _updated_at, UUID(),_username, _email, _password, _created_at, _updated_at, _USER, _CURRENT_CONNECTIONS, _TOTAL_CONNECTIONS, UUID(),_username, _email, _password, _is_admin, _created_at, _updated_at, UUID(),_username, _email, _password, _is_admin, _created_at, _updated_at, UUID(),_username, _email, _password, _created_at, _updated_at, UUID(),_username, _email, _password, _created_at, _updated_at, _USER, _CURRENT_CONNECTIONS, _TOTAL_CONNECTIONS, UUID(),_username, _email, _password, _is_admin, _created_at, _updated_at, UUID(),_username, _email, _password, _is_admin, _created_at, _updated_at, UUID(),_username, _email, _password, _created_at, _updated_at, UUID(),_username, _email, _password, _created_at, _updated_at, _USER, _CURRENT_CONNECTIONS, _TOTAL_CONNECTIONS, UUID(),_username, _email, _password, _is_admin, _created_at, _updated_at, UUID(),_username, _email, _password, _is_admin, _created_at, _updated_at, UUID(),_username, _email, _password, _created_at, _updated_at, UUID(),_username, _email, _password, _created_at, _updated_at, _USER, _CURRENT_CONNECTIONS, _TOTAL_CONNECTIONS) ;
    
    END$$
    DELIMITER ;
    
    